-- QuickEats Complete Data Migration Script for Somee MS SQL
-- Generated from (localdb)\mssqllocaldb

-- =============================================
-- Table: Users (29 rows)
-- =============================================
SET IDENTITY_INSERT [Users] ON;
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 4) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (4, N'Admin', N'admin2@gmail.com', N'$2a$11$ik6CCCisTpk29UlQs77cVu0RGeNrinBCPNmDuvlT1yJ.sNQe/Xh9G', N'Admin', '2026-07-14 05:17:17.571', N'9999999999', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 1003) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (1003, N'Pizza Owner', N'owner@gmail.com', N'$2a$11$VB25VL7SmkQ45LklZfwEceee0EIGOgwl.t.lN8DkWrXWYf4RY0Ate', N'Owner', '2026-07-14 09:43:12.632', N'9999999999', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 1004) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (1004, N'John', N'customer@gmail.com', N'$2a$11$6wpLfJnRkkX6rUQbSyLlRujCMRUapa.EQc.ZQh7S06bznqDPhx4IC', N'Customer', '2026-07-15 05:49:07.386', N'9876543210', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 1005) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (1005, N'Mrudula', N'mrudula@gmail.com', N'$2a$11$QO2SS9LQ3I43dxjMSk6L0.8hMJY7DOzYd96vCcx5REVNPN.c4aJMe', N'Customer', '2026-07-25 10:59:03.292', N'8978978978', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 1006) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (1006, N'Mrudula', N'mrudula@gmail.com', N'$2a$11$dgA/veS2TUkHXbD/PCeK4eyiMGWS5FFWv8LHrMovLlIiPdTLy2cnC', N'Customer', '2026-07-25 10:59:02.417', N'8978978978', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 1007) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (1007, N'Mrudula', N'mrudula@gmail.com', N'$2a$11$pc1EbCGzB4jlsyjjrugcWeIvzuari7gYVdB8oMg6ycTOPMQ8YHaSS', N'Customer', '2026-07-25 10:59:02.419', N'8978978978', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 1008) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (1008, N'Mrudula', N'mrudula@gmail.com', N'$2a$11$SdzYdnvrRVJTOMHTHk.GgeMFmBflQbtcmzJOYppnCpUj/9Pm6ctNO', N'Customer', '2026-07-25 10:59:02.417', N'8978978978', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 1009) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (1009, N'Mrudula', N'mrudula@gmail.com', N'$2a$11$jOznvp4l0IP3ELGit9pJ5.CPb6E8OAp9u.1vOCtXRLMO8Z8HSjo2O', N'Customer', '2026-07-25 10:59:03.493', N'8978978978', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 1010) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (1010, N'Mrudula', N'mrudula@gmail.com', N'$2a$11$n24dNf/KDEqHXxEnImiNAesk1bAWQj2ZDaZeGXedlkM60jLdGmicS', N'Customer', '2026-07-25 10:59:03.708', N'8978978978', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 1011) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (1011, N'Nisha', N'nisha12@gmail.com', N'$2a$11$q740AbhwGcZaM29.Q3ZJf.rI7AiPP627kMmkj9nFMs2toVtOnpxj2', N'Customer', '2026-07-25 11:07:06.105', N'7897897897', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 1012) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (1012, N'TestUser', N'test@t.com', N'$2a$11$HrU9E8V0vkbiKMvm27NL2O7oJEyhcCinW2F6tRrcaD3nhcKhDk6Oa', N'Customer', '2026-08-14 04:58:19.818', N'1234567890', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 1013) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (1013, N'OwnerOne', N'owner1@test.com', N'$2a$11$1r091zZ2yXtEHivCiq2S1uldCuB6DB2arbE7baUcEDsdIjWVF.u0K', N'Owner', '2026-08-14 05:12:36.232', N'9999999991', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 1014) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (1014, N'SuperAdmin', N'admin@test.com', N'$2a$11$nZ36qyEJRyrMs5Z/lqBFMueV8AgC2vRXcBOA1K7N1hPnftAQ1uuC6', N'Admin', '2026-08-14 05:20:09.755', N'9000000000', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 1015) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (1015, N'Rider', N'rider@test.com', N'$2a$11$R5kao2q9lWNES9WMfDu82OVJ4qohGhz5j1JSJD33XdBT5FCdmhVPq', N'DeliveryPartner', '2026-08-14 05:48:27.147', N'9111111111', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 1016) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (1016, N'MenuTest', N'menutest@quickeats.com', N'$2a$11$juexpyLJBOEQsDm4EMenZObM6GegVIHsOh1NK7vln4Iuhur49jMty', N'Customer', '2026-08-14 09:11:06.451', N'9999999999', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 1017) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (1017, N'Test Customer', N'testcustomer@test.com', N'$2a$11$EKWjh1gsxERixSo.InJJVuzBatRajUud/v6Bet6txtnztRCoXO6s2', N'Customer', '2026-08-27 02:54:49.780', N'1234567890', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 1018) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (1018, N'Test Owner', N'testowner@test.com', N'$2a$11$mi8ssGN0WIcGn.fuEQjFcuFFAYc43xoApynWlcoJV/GCaK27G8eaK', N'Owner', '2026-08-27 02:55:16.600', N'9876543210', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 1019) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (1019, N'Test Admin', N'testadmin@test.com', N'$2a$11$NWxWNpBepDlsHcAyHwp4ker3MpUspBemF1S0LTNdyli0ag5i/QbbS', N'Customer', '2026-08-27 02:55:16.772', N'5555555555', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 1020) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (1020, N'Alice', N'alice@test.com', N'$2a$11$iRRuddUUOB0QHNzEsGKJLuKJu00prohtLrJfpoSF7UZi7jKKdzLY.', N'Customer', '2026-08-27 03:35:52.025', N'1111111111', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 1021) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (1021, N'Owner Bob', N'bob@test.com', N'$2a$11$w/SQdxDrSLImG7tl5/Qteu/3Om3lTsDe.OFcghqBTt6sTf7o//9Ge', N'Owner', '2026-08-27 03:35:52.529', N'2222222222', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 1022) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (1022, N'Owner Carol', N'carol@test.com', N'$2a$11$g/tW7UqBM8U21CW9o2mQs.8wv.W4/FmpN2De/E/LZ7oGM4qzLpRMW', N'Owner', '2026-08-27 03:35:52.747', N'3333333333', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 1023) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (1023, N'Final Customer', N'finalcustomer@test.com', N'$2a$11$WgqV.hb09jNSGk6MCMQEhu5po4nBpd7nyeXyEy6OB19jr6eH7koxq', N'Customer', '2026-08-27 03:53:48.834', N'5551001001', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 1024) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (1024, N'Final Owner', N'finalowner@test.com', N'$2a$11$mD3Fyl/DqC67Y9oKL73iKOKrCo/.uJfw8f/23Yjo8PmD27wSp2ElG', N'Owner', '2026-08-27 03:55:03.145', N'5552002000', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 1025) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (1025, N'Other Owner', N'otherowner@test.com', N'$2a$11$JqI.ahOcc04PX3OJcgcq7.VPAhemG9wnR8REdvMXM3yMYBzUvkMWO', N'Owner', '2026-08-27 03:55:04.104', N'5553003000', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 1026) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (1026, N'Fresh Admin', N'freshadmin@test.com', N'$2a$11$iNWGCXB7wwv.vVoYOYhHCeVPvw/HwJU57rvZlr/XsMpNr1MiciTRe', N'Customer', '2026-08-27 03:57:00.481', N'1234567890', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 2023) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (2023, N'Owner B Test', N'ownerb@test.com', N'$2a$11$b/3itHV6yIhPReL/hQBMxOeysjWxI9zxsA9P2rFQ9mt0HPqNfn6QO', N'Owner', '2026-08-27 07:08:06.910', N'5550002', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 3023) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (3023, N'OwnerATest', N'ownera_iso@test.com', N'$2a$11$KxAa4Tu08Z4wI30jJT0Bwef7Za9mgxXOX28KVi0bPSiI28F8L78hy', N'Owner', '2026-08-27 07:30:13.888', N'1111111111', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 3024) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (3024, N'OwnerBTest', N'ownerb_iso@test.com', N'$2a$11$Is8dTAxhSMP59O4AACZn2.5J3EmOQeRA6Vq.r4125x/6SbNnbk5bO', N'Owner', '2026-08-27 07:30:14.452', N'2222222222', N'');
IF NOT EXISTS (SELECT 1 FROM [Users] WHERE [Id] = 3025) INSERT INTO [Users] ([Id], [Name], [Email], [PasswordHash], [Role], [CreatedAt], [PhoneNumber], [ProfileImageUrl]) VALUES (3025, N'Test User', N'testuser_1772019233@quickeats.com', N'$2a$11$uRRl.tKBDE1UwqPpRd8pCOdZKUdxnXYf9/OPE/vbuKjxLhDjLxtp.', N'Customer', '2026-09-02 05:16:22.219', N'9876543210', N'');
SET IDENTITY_INSERT [Users] OFF;

-- =============================================
-- Table: Restaurants (16 rows)
-- =============================================
SET IDENTITY_INSERT [Restaurants] ON;
IF NOT EXISTS (SELECT 1 FROM [Restaurants] WHERE [Id] = 1) INSERT INTO [Restaurants] ([Id], [Name], [Description], [Address], [PhoneNumber], [ImageUrl], [IsActive], [CreatedAt], [OwnerId], [ClosingTime], [OpeningTime], [DeliveryCharge], [MinimumOrder]) VALUES (1, N'Dominos', N'Best pizza delivery in town', N'123 Pizza Street, Mumbai', N'9876543210', N'/uploads/restaurants/Dominos.webp', 1, '2026-07-14 10:51:56.751', 1003, N'', N'', 30.00, 200.00);
IF NOT EXISTS (SELECT 1 FROM [Restaurants] WHERE [Id] = 3) INSERT INTO [Restaurants] ([Id], [Name], [Description], [Address], [PhoneNumber], [ImageUrl], [IsActive], [CreatedAt], [OwnerId], [ClosingTime], [OpeningTime], [DeliveryCharge], [MinimumOrder]) VALUES (3, N'Burger King', N'Flame-grilled burgers and more', N'456 Burger Lane, Delhi', N'9876543211', N'/uploads/restaurants/burgerking.jpg', 1, '2026-07-14 10:59:22.888', 1003, N'', N'', 25.00, 150.00);
IF NOT EXISTS (SELECT 1 FROM [Restaurants] WHERE [Id] = 4) INSERT INTO [Restaurants] ([Id], [Name], [Description], [Address], [PhoneNumber], [ImageUrl], [IsActive], [CreatedAt], [OwnerId], [ClosingTime], [OpeningTime], [DeliveryCharge], [MinimumOrder]) VALUES (4, N'Biryani House', N'Authentic Hyderabadi Biryani', N'789 Biryani Road, Hyderabad', N'9876543212', N'/uploads/restaurants/biryani.jpg', 1, '2026-07-14 10:59:24.199', 1003, N'', N'', 35.00, 200.00);
IF NOT EXISTS (SELECT 1 FROM [Restaurants] WHERE [Id] = 5) INSERT INTO [Restaurants] ([Id], [Name], [Description], [Address], [PhoneNumber], [ImageUrl], [IsActive], [CreatedAt], [OwnerId], [ClosingTime], [OpeningTime], [DeliveryCharge], [MinimumOrder]) VALUES (5, N'Owner One Pizzeria', N'Fresh wood fired pizzas', N'Mumbai, India', N'9888877777', N'/uploads/restaurants/Dominos.webp', 1, '2026-08-14 05:13:14.652', 1013, N'', N'', 0.00, 0.00);
IF NOT EXISTS (SELECT 1 FROM [Restaurants] WHERE [Id] = 10) INSERT INTO [Restaurants] ([Id], [Name], [Description], [Address], [PhoneNumber], [ImageUrl], [IsActive], [CreatedAt], [OwnerId], [ClosingTime], [OpeningTime], [DeliveryCharge], [MinimumOrder]) VALUES (10, N'Spice Garden', N'North Indian cuisine with authentic spices', N'321 Spice Nagar, Jaipur', N'9876543220', N'/uploads/restaurants/spice-garden.jpg', 1, '2026-08-25 09:47:31.840', 1003, N'23:00', N'10:00', 40.00, 250.00);
IF NOT EXISTS (SELECT 1 FROM [Restaurants] WHERE [Id] = 11) INSERT INTO [Restaurants] ([Id], [Name], [Description], [Address], [PhoneNumber], [ImageUrl], [IsActive], [CreatedAt], [OwnerId], [ClosingTime], [OpeningTime], [DeliveryCharge], [MinimumOrder]) VALUES (11, N'Sushi World', N'Japanese sushi and ramen', N'555 Tokyo Street, Bangalore', N'9876543221', N'/uploads/restaurants/sushi-world.jpg', 1, '2026-08-25 09:47:31.840', 1003, N'22:00', N'11:00', 50.00, 300.00);
IF NOT EXISTS (SELECT 1 FROM [Restaurants] WHERE [Id] = 12) INSERT INTO [Restaurants] ([Id], [Name], [Description], [Address], [PhoneNumber], [ImageUrl], [IsActive], [CreatedAt], [OwnerId], [ClosingTime], [OpeningTime], [DeliveryCharge], [MinimumOrder]) VALUES (12, N'Taco Fiesta', N'Mexican tacos and burritos', N'888 Mexico Lane, Pune', N'9876543222', N'/uploads/restaurants/taco-fiesta.webp', 1, '2026-08-25 09:47:31.843', 1003, N'21:00', N'09:00', 20.00, 100.00);
IF NOT EXISTS (SELECT 1 FROM [Restaurants] WHERE [Id] = 13) INSERT INTO [Restaurants] ([Id], [Name], [Description], [Address], [PhoneNumber], [ImageUrl], [IsActive], [CreatedAt], [OwnerId], [ClosingTime], [OpeningTime], [DeliveryCharge], [MinimumOrder]) VALUES (13, N'Dragon Wok', N'Chinese stir-fry and noodles', N'111 Dragon Road, Chennai', N'9876543223', N'/uploads/restaurants/dragon-wok.webp', 1, '2026-08-25 09:47:31.843', 1003, N'22:00', N'10:00', 30.00, 150.00);
IF NOT EXISTS (SELECT 1 FROM [Restaurants] WHERE [Id] = 14) INSERT INTO [Restaurants] ([Id], [Name], [Description], [Address], [PhoneNumber], [ImageUrl], [IsActive], [CreatedAt], [OwnerId], [ClosingTime], [OpeningTime], [DeliveryCharge], [MinimumOrder]) VALUES (14, N'Pasta Palace', N'Italian pasta and risotto', N'222 Italy Street, Goa', N'9876543224', N'/uploads/restaurants/pasta-palace.webp', 1, '2026-08-25 09:47:31.843', 1003, N'23:00', N'11:00', 35.00, 200.00);
IF NOT EXISTS (SELECT 1 FROM [Restaurants] WHERE [Id] = 15) INSERT INTO [Restaurants] ([Id], [Name], [Description], [Address], [PhoneNumber], [ImageUrl], [IsActive], [CreatedAt], [OwnerId], [ClosingTime], [OpeningTime], [DeliveryCharge], [MinimumOrder]) VALUES (15, N'Burger Barn', N'Gourmet burgers and shakes', N'444 Barn Lane, Kolkata', N'9876543225', N'/uploads/restaurants/burger-barn.webp', 1, '2026-08-25 09:47:31.843', 1013, N'22:00', N'09:00', 15.00, 100.00);
IF NOT EXISTS (SELECT 1 FROM [Restaurants] WHERE [Id] = 16) INSERT INTO [Restaurants] ([Id], [Name], [Description], [Address], [PhoneNumber], [ImageUrl], [IsActive], [CreatedAt], [OwnerId], [ClosingTime], [OpeningTime], [DeliveryCharge], [MinimumOrder]) VALUES (16, N'Curry House', N'South Indian curries and dosas', N'666 Curry Road, Cochin', N'9876543226', N'/uploads/restaurants/curry-house.webp', 1, '2026-08-25 09:47:31.843', 1013, N'21:00', N'08:00', 25.00, 120.00);
IF NOT EXISTS (SELECT 1 FROM [Restaurants] WHERE [Id] = 17) INSERT INTO [Restaurants] ([Id], [Name], [Description], [Address], [PhoneNumber], [ImageUrl], [IsActive], [CreatedAt], [OwnerId], [ClosingTime], [OpeningTime], [DeliveryCharge], [MinimumOrder]) VALUES (17, N'Grill Master', N'BBQ and grilled delicacies', N'777 Grill Avenue, Lucknow', N'9876543227', N'/uploads/restaurants/grill-master.webp', 1, '2026-08-25 09:47:31.843', 1013, N'23:00', N'12:00', 45.00, 250.00);
IF NOT EXISTS (SELECT 1 FROM [Restaurants] WHERE [Id] = 19) INSERT INTO [Restaurants] ([Id], [Name], [Description], [Address], [PhoneNumber], [ImageUrl], [IsActive], [CreatedAt], [OwnerId], [ClosingTime], [OpeningTime], [DeliveryCharge], [MinimumOrder]) VALUES (19, N'Owner''s Kitchen', N'Delicious home-cooked meals', N'456 Main Street, Foodville', N'5551234567', N'/uploads/restaurants/spice-garden.jpg', 1, '2026-08-27 02:56:53.777', 1018, N'23:00', N'10:00', 3.50, 15.00);
IF NOT EXISTS (SELECT 1 FROM [Restaurants] WHERE [Id] = 20) INSERT INTO [Restaurants] ([Id], [Name], [Description], [Address], [PhoneNumber], [ImageUrl], [IsActive], [CreatedAt], [OwnerId], [ClosingTime], [OpeningTime], [DeliveryCharge], [MinimumOrder]) VALUES (20, N'Bob''s Burgers', N'Best burgers', N'100 Main St', N'2222222222', N'/uploads/restaurants/bobs-burgers.webp', 1, '2026-08-27 03:35:53.635', 1021, N'22:00', N'09:00', 2.99, 10.00);
IF NOT EXISTS (SELECT 1 FROM [Restaurants] WHERE [Id] = 21) INSERT INTO [Restaurants] ([Id], [Name], [Description], [Address], [PhoneNumber], [ImageUrl], [IsActive], [CreatedAt], [OwnerId], [ClosingTime], [OpeningTime], [DeliveryCharge], [MinimumOrder]) VALUES (21, N'Carol''s Curry', N'Spicy curries', N'200 Oak Ave', N'3333333333', N'/uploads/restaurants/carols-curry.webp', 1, '2026-08-27 03:35:53.767', 1022, N'23:00', N'10:00', 3.50, 15.00);
IF NOT EXISTS (SELECT 1 FROM [Restaurants] WHERE [Id] = 1022) INSERT INTO [Restaurants] ([Id], [Name], [Description], [Address], [PhoneNumber], [ImageUrl], [IsActive], [CreatedAt], [OwnerId], [ClosingTime], [OpeningTime], [DeliveryCharge], [MinimumOrder]) VALUES (1022, N'Owner B Burger Joint', N'Burgers', N'456 Burger St', N'5550002', N'/uploads/restaurants/burger-barn.webp', 1, '2026-08-27 07:08:24.453', 2023, N'22:00', N'09:00', 30.00, 50.00);
SET IDENTITY_INSERT [Restaurants] OFF;

-- =============================================
-- Table: MenuItems (54 rows)
-- =============================================
SET IDENTITY_INSERT [MenuItems] ON;
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 8) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (8, 1, N'Veg Pizza', N'Cheese burst Pizza', 299.00, N'/uploads/menu/veg-pizza.png', 1, N'Pizza', 0.00, 0, 0);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 9) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (9, 1, N'Margherita Pizza', N'Classic cheese pizza', 249.00, N'/uploads/menu/margherita-pizza.webp', 1, N'Pizza', 10.00, 1, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 10) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (10, 1, N'Pepperoni Pizza', N'Classic pepperoni with mozzarella cheese', 399.00, N'/uploads/menu/pepperoni-pizza.jpg', 1, N'Pizza', 10.00, 1, 0);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 11) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (11, 1, N'Farm House Pizza', N'Fresh vegetables and cheese', 349.00, N'/uploads/menu/farmhouse-pizza.webp', 1, N'Pizza', 5.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 12) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (12, 1, N'Chicken BBQ Pizza', N'Smoky BBQ chicken pizza', 449.00, N'/uploads/menu/bbq-chicken-pizza.jpg', 1, N'Pizza', 0.00, 1, 0);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 13) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (13, 1, N'Garlic Bread', N'Crispy garlic bread with herbs', 129.00, N'/uploads/menu/garlic-bread.webp', 1, N'Starters', 0.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 14) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (14, 1, N'Cola', N'Chilled Coca-Cola 500ml', 49.00, N'/uploads/menu/cola.jpg', 1, N'Beverages', 0.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 20) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (20, 3, N'Whopper', N'Flame-grilled beef patty with toppings', 299.00, N'/uploads/menu/whopper.webp', 1, N'Burgers', 10.00, 1, 0);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 21) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (21, 3, N'Veggie Burger', N'Crispy veggie patty', 199.00, N'/uploads/menu/veggie-burger.webp', 1, N'Burgers', 0.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 22) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (22, 3, N'Chicken Royale', N'Crispy chicken fillet burger', 259.00, N'/uploads/menu/chicken-burger.png', 1, N'Burgers', 5.00, 1, 0);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 23) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (23, 3, N'French Fries', N'Golden crispy fries', 99.00, N'/uploads/menu/french-fries.webp', 1, N'Starters', 0.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 24) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (24, 3, N'Chocolate Shake', N'Rich chocolate milkshake', 149.00, N'/uploads/menu/chocolate-shake.webp', 1, N'Beverages', 0.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 30) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (30, 4, N'Chicken Biryani', N'Hyderabadi chicken biryani', 299.00, N'/uploads/menu/chicken-biryani.webp', 1, N'Biryani', 10.00, 1, 0);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 31) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (31, 4, N'Veg Biryani', N'Mixed vegetable biryani', 229.00, N'/uploads/menu/veg-biryani.webp', 1, N'Biryani', 5.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 32) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (32, 4, N'Mutton Biryani', N'Tender mutton biryani', 399.00, N'/uploads/menu/mutton-biryani.webp', 1, N'Biryani', 0.00, 1, 0);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 33) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (33, 4, N'Chicken 65', N'Spicy fried chicken', 199.00, N'/uploads/menu/chicken-65.webp', 1, N'Starters', 0.00, 1, 0);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 34) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (34, 4, N'Raita', N'Cool yogurt raita', 49.00, N'/uploads/menu/raita.jpg', 1, N'Starters', 0.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 40) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (40, 5, N'Paneer Tikka Pizza', N'Smoky paneer with tikka sauce', 329.00, N'/uploads/menu/paneer-tikka-pizza.webp', 1, N'Pizza', 15.00, 1, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 41) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (41, 5, N'Meat Lovers Pizza', N'Triple meat pizza', 499.00, N'/uploads/menu/meat-lovers-pizza.jpg', 1, N'Pizza', 0.00, 0, 0);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 50) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (50, 10, N'Butter Chicken', N'Creamy butter chicken curry', 349.00, N'/uploads/menu/butter-chicken.webp', 1, N'Main Course', 10.00, 1, 0);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 51) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (51, 10, N'Paneer Butter Masala', N'Rich paneer in butter sauce', 279.00, N'/uploads/menu/paneer-butter-masala.webp', 1, N'Main Course', 5.00, 1, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 52) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (52, 10, N'Dal Makhani', N'Slow-cooked black lentils', 199.00, N'/uploads/menu/dal-makhani.webp', 1, N'Main Course', 0.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 53) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (53, 10, N'Tandoori Roti', N'Fresh tandoor-baked bread', 39.00, N'/uploads/menu/tandoori-roti.webp', 1, N'Main Course', 0.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 54) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (54, 10, N'Gulab Jamun', N'Warm milk dumplings in syrup', 99.00, N'/uploads/menu/gulab-jamun.webp', 1, N'Desserts', 0.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 55) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (55, 10, N'Masala Chai', N'Spiced Indian tea', 49.00, N'/uploads/menu/masala-chai.jpg', 1, N'Beverages', 0.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 60) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (60, 11, N'Salmon Sushi Roll', N'Fresh salmon with sushi rice', 499.00, N'/uploads/menu/sushi-roll.webp', 1, N'Main Course', 10.00, 1, 0);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 61) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (61, 11, N'Veg Tempura', N'Crispy vegetable tempura', 299.00, N'/uploads/menu/veg-tempura.jpg', 1, N'Starters', 0.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 62) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (62, 11, N'Chicken Ramen', N'Rich broth with noodles', 349.00, N'/uploads/menu/chicken-ramen.webp', 1, N'Main Course', 0.00, 1, 0);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 63) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (63, 11, N'Miso Soup', N'Traditional Japanese soup', 149.00, N'/uploads/menu/miso-soup.jpg', 1, N'Starters', 0.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 70) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (70, 12, N'Chicken Taco', N'Spiced chicken in soft shell', 179.00, N'/uploads/menu/chicken-taco.webp', 1, N'Main Course', 10.00, 1, 0);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 71) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (71, 12, N'Veg Burrito Bowl', N'Rice, beans, veggies, salsa', 229.00, N'/uploads/menu/burrito-bowl.webp', 1, N'Main Course', 5.00, 1, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 72) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (72, 12, N'Nachos Supreme', N'Loaded cheese nachos', 199.00, N'/uploads/menu/nachos-supreme.webp', 1, N'Starters', 0.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 73) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (73, 12, N'Churros', N'Cinnamon sugar churros', 129.00, N'/uploads/menu/churros.webp', 1, N'Desserts', 0.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 80) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (80, 13, N'Hakka Noodles', N'Indo-Chinese noodles', 199.00, N'/uploads/menu/hakka-noodles.webp', 1, N'Main Course', 0.00, 1, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 81) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (81, 13, N'Manchurian', N'Veg manchurian gravy', 229.00, N'/uploads/menu/manchurian.jpg', 1, N'Main Course', 5.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 82) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (82, 13, N'Chilli Chicken', N'Spicy fried chicken', 299.00, N'/uploads/menu/chilli-chicken.webp', 1, N'Main Course', 10.00, 1, 0);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 83) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (83, 13, N'Spring Rolls', N'Crispy vegetable spring rolls', 149.00, N'/uploads/menu/spring-rolls.webp', 1, N'Starters', 0.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 90) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (90, 14, N'Spaghetti Carbonara', N'Classic Italian pasta', 349.00, N'/uploads/menu/spaghetti-carbonara.webp', 1, N'Main Course', 5.00, 1, 0);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 91) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (91, 14, N'Penne Arrabbiata', N'Spicy tomato pasta', 279.00, N'/uploads/menu/penne-arrabbiata.webp', 1, N'Main Course', 0.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 92) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (92, 14, N'Mushroom Risotto', N'Creamy mushroom rice', 399.00, N'/uploads/menu/mushroom-risotto.jpg', 1, N'Main Course', 10.00, 1, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 93) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (93, 14, N'Tiramisu', N'Italian coffee dessert', 199.00, N'/uploads/menu/tiramisu.webp', 1, N'Desserts', 0.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 100) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (100, 15, N'Classic Smash Burger', N'Double smashed beef patty', 249.00, N'/uploads/menu/classic-smash-burger.jpg', 1, N'Burgers', 0.00, 1, 0);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 101) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (101, 15, N'Truffle Fries', N'Truffle oil seasoned fries', 179.00, N'/uploads/menu/truffle-fries.webp', 1, N'Starters', 0.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 102) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (102, 15, N'Oreo Shake', N'Oreo cookie milkshake', 149.00, N'/uploads/menu/oreo-shake.jpg', 1, N'Beverages', 0.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 110) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (110, 16, N'Masala Dosa', N'Crispy dosa with potato filling', 129.00, N'/uploads/menu/masala-dosa.webp', 1, N'Main Course', 0.00, 1, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 111) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (111, 16, N'Idli Sambar', N'Steamed rice cakes with sambar', 99.00, N'/uploads/menu/idli-sambar.jpg', 1, N'Main Course', 0.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 112) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (112, 16, N'Chettinad Chicken', N'Spicy Chettinad chicken curry', 299.00, N'/uploads/menu/chettinad-chicken.jpg', 1, N'Main Course', 10.00, 1, 0);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 113) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (113, 16, N'Filter Coffee', N'South Indian filter coffee', 39.00, N'/uploads/menu/filter-coffee.webp', 1, N'Beverages', 0.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 120) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (120, 17, N'Grilled Chicken', N'Herb-marinated grilled chicken', 349.00, N'/uploads/menu/grilled-chicken.jpg', 1, N'Main Course', 5.00, 1, 0);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 121) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (121, 17, N'BBQ Ribs', N'Slow-smoked pork ribs', 499.00, N'/uploads/menu/bbq-ribs.jpg', 1, N'Main Course', 0.00, 1, 0);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 122) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (122, 17, N'Grilled Paneer', N'Smoky grilled paneer tikka', 249.00, N'/uploads/menu/grilled-paneer.jpg', 1, N'Main Course', 10.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 123) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (123, 17, N'Corn on the Cob', N'Grilled sweet corn', 79.00, N'/uploads/menu/corn-on-the-cob.jpg', 1, N'Starters', 0.00, 0, 1);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 125) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (125, 20, N'Classic Burger', N'Juicy', 8.99, N'/uploads/menu/classic-burger.jpg', 1, N'Burgers', 0.00, 1, 0);
IF NOT EXISTS (SELECT 1 FROM [MenuItems] WHERE [Id] = 126) INSERT INTO [MenuItems] ([Id], [RestaurantId], [Name], [Description], [Price], [ImageUrl], [IsAvailable], [Category], [DiscountPercent], [IsBestseller], [IsVeg]) VALUES (126, 21, N'Butter Chicken', N'Creamy', 12.99, N'/uploads/menu/butter-chicken.webp', 1, N'Main Course', 0.00, 0, 0);
SET IDENTITY_INSERT [MenuItems] OFF;

-- =============================================
-- Table: Coupons (7 rows)
-- =============================================
SET IDENTITY_INSERT [Coupons] ON;
IF NOT EXISTS (SELECT 1 FROM [Coupons] WHERE [Id] = 1) INSERT INTO [Coupons] ([Id], [Code], [Description], [MinimumOrderAmount], [DiscountAmount], [ExpiryDate], [IsActive]) VALUES (1, N'WELCOME50', N'Get 50 off on your first order', 300.00, 50.00, '2027-12-31 00:00:00.000', 1);
IF NOT EXISTS (SELECT 1 FROM [Coupons] WHERE [Id] = 2) INSERT INTO [Coupons] ([Id], [Code], [Description], [MinimumOrderAmount], [DiscountAmount], [ExpiryDate], [IsActive]) VALUES (2, N'SAVE20', N'20% off on orders above 500', 500.00, 100.00, '2027-12-31 00:00:00.000', 1);
IF NOT EXISTS (SELECT 1 FROM [Coupons] WHERE [Id] = 3) INSERT INTO [Coupons] ([Id], [Code], [Description], [MinimumOrderAmount], [DiscountAmount], [ExpiryDate], [IsActive]) VALUES (3, N'FLAT100', N'Flat 100 off on orders above 800', 800.00, 100.00, '2027-12-31 00:00:00.000', 1);
IF NOT EXISTS (SELECT 1 FROM [Coupons] WHERE [Id] = 4) INSERT INTO [Coupons] ([Id], [Code], [Description], [MinimumOrderAmount], [DiscountAmount], [ExpiryDate], [IsActive]) VALUES (4, N'FREEDEL', N'Free delivery on orders above 200', 200.00, 40.00, '2027-12-31 00:00:00.000', 1);
IF NOT EXISTS (SELECT 1 FROM [Coupons] WHERE [Id] = 600) INSERT INTO [Coupons] ([Id], [Code], [Description], [MinimumOrderAmount], [DiscountAmount], [ExpiryDate], [IsActive]) VALUES (600, N'WELCOME20', N'Welcome discount - Rs 20 off', 100.00, 20.00, '2026-11-25 09:50:13.346', 1);
IF NOT EXISTS (SELECT 1 FROM [Coupons] WHERE [Id] = 601) INSERT INTO [Coupons] ([Id], [Code], [Description], [MinimumOrderAmount], [DiscountAmount], [ExpiryDate], [IsActive]) VALUES (601, N'SAVE50', N'Save Rs 50 on orders above 500', 500.00, 50.00, '2026-09-25 09:50:13.346', 1);
IF NOT EXISTS (SELECT 1 FROM [Coupons] WHERE [Id] = 602) INSERT INTO [Coupons] ([Id], [Code], [Description], [MinimumOrderAmount], [DiscountAmount], [ExpiryDate], [IsActive]) VALUES (602, N'FOOD10', N'10% off on first order', 200.00, 30.00, '2026-10-25 09:50:13.346', 1);
SET IDENTITY_INSERT [Coupons] OFF;

-- =============================================
-- Table: Reviews (6 rows)
-- =============================================
SET IDENTITY_INSERT [Reviews] ON;
IF NOT EXISTS (SELECT 1 FROM [Reviews] WHERE [Id] = 500) INSERT INTO [Reviews] ([Id], [CustomerId], [RestaurantId], [Rating], [Comment], [CreatedAt]) VALUES (500, 1004, 1, 4, N'Great pizza! Fast delivery.', '2026-08-21 09:50:13.333');
IF NOT EXISTS (SELECT 1 FROM [Reviews] WHERE [Id] = 501) INSERT INTO [Reviews] ([Id], [CustomerId], [RestaurantId], [Rating], [Comment], [CreatedAt]) VALUES (501, 1004, 3, 3, N'Burgers were okay, could be better.', '2026-08-23 09:50:13.333');
IF NOT EXISTS (SELECT 1 FROM [Reviews] WHERE [Id] = 502) INSERT INTO [Reviews] ([Id], [CustomerId], [RestaurantId], [Rating], [Comment], [CreatedAt]) VALUES (502, 1004, 4, 5, N'Amazing biryani! Best in town.', '2026-08-24 09:50:13.333');
IF NOT EXISTS (SELECT 1 FROM [Reviews] WHERE [Id] = 503) INSERT INTO [Reviews] ([Id], [CustomerId], [RestaurantId], [Rating], [Comment], [CreatedAt]) VALUES (503, 1004, 10, 4, N'Delicious butter chicken!', '2026-08-25 08:50:13.333');
IF NOT EXISTS (SELECT 1 FROM [Reviews] WHERE [Id] = 504) INSERT INTO [Reviews] ([Id], [CustomerId], [RestaurantId], [Rating], [Comment], [CreatedAt]) VALUES (504, 1020, 20, 5, N'Amazing burgers!', '2026-08-27 03:35:55.024');
IF NOT EXISTS (SELECT 1 FROM [Reviews] WHERE [Id] = 505) INSERT INTO [Reviews] ([Id], [CustomerId], [RestaurantId], [Rating], [Comment], [CreatedAt]) VALUES (505, 1023, 1, 5, N'Final test - excellent!', '2026-08-27 03:53:51.267');
SET IDENTITY_INSERT [Reviews] OFF;

-- =============================================
-- Table: Orders (15 rows)
-- =============================================
SET IDENTITY_INSERT [Orders] ON;
IF NOT EXISTS (SELECT 1 FROM [Orders] WHERE [Id] = 2) INSERT INTO [Orders] ([Id], [UserId], [TotalAmount], [Status], [CreatedAt], [MenuItemId], [DeliveryAddress], [PaymentMethod], [PhoneNumber], [RestaurantId]) VALUES (2, 1004, 598.00, N'Confirmed', '2026-07-15 06:38:07.868', NULL, N'', N'', N'', 1);
IF NOT EXISTS (SELECT 1 FROM [Orders] WHERE [Id] = 3) INSERT INTO [Orders] ([Id], [UserId], [TotalAmount], [Status], [CreatedAt], [MenuItemId], [DeliveryAddress], [PaymentMethod], [PhoneNumber], [RestaurantId]) VALUES (3, 1012, 598.00, N'Delivered', '2026-08-14 04:59:56.237', NULL, N'123 Main Street, Delhi', N'UPI', N'1234567890', 4);
IF NOT EXISTS (SELECT 1 FROM [Orders] WHERE [Id] = 5) INSERT INTO [Orders] ([Id], [UserId], [TotalAmount], [Status], [CreatedAt], [MenuItemId], [DeliveryAddress], [PaymentMethod], [PhoneNumber], [RestaurantId]) VALUES (5, 1016, 598.00, N'Pending', '2026-08-14 09:13:08.359', NULL, N'Bandra, Mumbai', N'Cash On Delivery', N'9999999999', 4);
IF NOT EXISTS (SELECT 1 FROM [Orders] WHERE [Id] = 100) INSERT INTO [Orders] ([Id], [UserId], [TotalAmount], [Status], [CreatedAt], [MenuItemId], [DeliveryAddress], [PaymentMethod], [PhoneNumber], [RestaurantId]) VALUES (100, 1004, 498.00, N'Delivered', '2026-08-20 09:50:13.330', NULL, N'123 Home Street, Mumbai', N'Online Payment', N'9876543210', 1);
IF NOT EXISTS (SELECT 1 FROM [Orders] WHERE [Id] = 101) INSERT INTO [Orders] ([Id], [UserId], [TotalAmount], [Status], [CreatedAt], [MenuItemId], [DeliveryAddress], [PaymentMethod], [PhoneNumber], [RestaurantId]) VALUES (101, 1004, 448.00, N'Delivered', '2026-08-22 09:50:13.330', NULL, N'123 Home Street, Mumbai', N'Cash On Delivery', N'9876543210', 3);
IF NOT EXISTS (SELECT 1 FROM [Orders] WHERE [Id] = 102) INSERT INTO [Orders] ([Id], [UserId], [TotalAmount], [Status], [CreatedAt], [MenuItemId], [DeliveryAddress], [PaymentMethod], [PhoneNumber], [RestaurantId]) VALUES (102, 1004, 548.00, N'Delivered', '2026-08-23 09:50:13.330', NULL, N'123 Home Street, Mumbai', N'Online Payment', N'9876543210', 4);
IF NOT EXISTS (SELECT 1 FROM [Orders] WHERE [Id] = 103) INSERT INTO [Orders] ([Id], [UserId], [TotalAmount], [Status], [CreatedAt], [MenuItemId], [DeliveryAddress], [PaymentMethod], [PhoneNumber], [RestaurantId]) VALUES (103, 1004, 398.00, N'Out for Delivery', '2026-08-25 07:50:13.330', NULL, N'123 Home Street, Mumbai', N'Online Payment', N'9876543210', 10);
IF NOT EXISTS (SELECT 1 FROM [Orders] WHERE [Id] = 104) INSERT INTO [Orders] ([Id], [UserId], [TotalAmount], [Status], [CreatedAt], [MenuItemId], [DeliveryAddress], [PaymentMethod], [PhoneNumber], [RestaurantId]) VALUES (104, 1004, 408.00, N'Preparing', '2026-08-25 08:50:13.330', NULL, N'123 Home Street, Mumbai', N'Cash On Delivery', N'9876543210', 12);
IF NOT EXISTS (SELECT 1 FROM [Orders] WHERE [Id] = 105) INSERT INTO [Orders] ([Id], [UserId], [TotalAmount], [Status], [CreatedAt], [MenuItemId], [DeliveryAddress], [PaymentMethod], [PhoneNumber], [RestaurantId]) VALUES (105, 1004, 548.00, N'Confirmed', '2026-08-25 09:20:13.330', NULL, N'123 Home Street, Mumbai', N'Online Payment', N'9876543210', 14);
IF NOT EXISTS (SELECT 1 FROM [Orders] WHERE [Id] = 106) INSERT INTO [Orders] ([Id], [UserId], [TotalAmount], [Status], [CreatedAt], [MenuItemId], [DeliveryAddress], [PaymentMethod], [PhoneNumber], [RestaurantId]) VALUES (106, 1004, 499.00, N'Pending', '2026-08-25 09:50:13.330', NULL, N'456 Office Lane, Delhi', N'Online Payment', N'9876543211', 11);
IF NOT EXISTS (SELECT 1 FROM [Orders] WHERE [Id] = 107) INSERT INTO [Orders] ([Id], [UserId], [TotalAmount], [Status], [CreatedAt], [MenuItemId], [DeliveryAddress], [PaymentMethod], [PhoneNumber], [RestaurantId]) VALUES (107, 1020, 17.98, N'Confirmed', '2026-08-27 03:35:54.096', NULL, N'789 Customer Lane', N'Cash', N'1111111111', 20);
IF NOT EXISTS (SELECT 1 FROM [Orders] WHERE [Id] = 108) INSERT INTO [Orders] ([Id], [UserId], [TotalAmount], [Status], [CreatedAt], [MenuItemId], [DeliveryAddress], [PaymentMethod], [PhoneNumber], [RestaurantId]) VALUES (108, 1020, 12.99, N'Pending', '2026-08-27 03:35:54.744', NULL, N'999 Other St', N'Cash', N'1111111111', 21);
IF NOT EXISTS (SELECT 1 FROM [Orders] WHERE [Id] = 109) INSERT INTO [Orders] ([Id], [UserId], [TotalAmount], [Status], [CreatedAt], [MenuItemId], [DeliveryAddress], [PaymentMethod], [PhoneNumber], [RestaurantId]) VALUES (109, 1020, 8.99, N'Pending', '2026-08-27 03:35:55.095', NULL, N'123 Test Street, Apt 4', N'Cash', N'1111111111', 20);
IF NOT EXISTS (SELECT 1 FROM [Orders] WHERE [Id] = 110) INSERT INTO [Orders] ([Id], [UserId], [TotalAmount], [Status], [CreatedAt], [MenuItemId], [DeliveryAddress], [PaymentMethod], [PhoneNumber], [RestaurantId]) VALUES (110, 1023, 798.00, N'Cancelled', '2026-08-27 03:53:50.363', NULL, N'123 Final Test St, Apt 1', N'Cash', N'5551001001', 1);
IF NOT EXISTS (SELECT 1 FROM [Orders] WHERE [Id] = 111) INSERT INTO [Orders] ([Id], [UserId], [TotalAmount], [Status], [CreatedAt], [MenuItemId], [DeliveryAddress], [PaymentMethod], [PhoneNumber], [RestaurantId]) VALUES (111, 1023, 399.00, N'Confirmed', '2026-08-27 03:53:51.473', NULL, N'456 Second St', N'Cash', N'5551001001', 1);
SET IDENTITY_INSERT [Orders] OFF;

-- =============================================
-- Table: OrderItems (22 rows)
-- =============================================
SET IDENTITY_INSERT [OrderItems] ON;
IF NOT EXISTS (SELECT 1 FROM [OrderItems] WHERE [Id] = 2) INSERT INTO [OrderItems] ([Id], [OrderId], [MenuItemId], [Quantity], [UnitPrice], [TotalPrice]) VALUES (2, 2, 8, 2, 299.00, 598.00);
IF NOT EXISTS (SELECT 1 FROM [OrderItems] WHERE [Id] = 3) INSERT INTO [OrderItems] ([Id], [OrderId], [MenuItemId], [Quantity], [UnitPrice], [TotalPrice]) VALUES (3, 3, 8, 2, 299.00, 598.00);
IF NOT EXISTS (SELECT 1 FROM [OrderItems] WHERE [Id] = 5) INSERT INTO [OrderItems] ([Id], [OrderId], [MenuItemId], [Quantity], [UnitPrice], [TotalPrice]) VALUES (5, 5, 8, 2, 299.00, 598.00);
IF NOT EXISTS (SELECT 1 FROM [OrderItems] WHERE [Id] = 200) INSERT INTO [OrderItems] ([Id], [OrderId], [MenuItemId], [Quantity], [UnitPrice], [TotalPrice]) VALUES (200, 100, 10, 1, 399.00, 399.00);
IF NOT EXISTS (SELECT 1 FROM [OrderItems] WHERE [Id] = 201) INSERT INTO [OrderItems] ([Id], [OrderId], [MenuItemId], [Quantity], [UnitPrice], [TotalPrice]) VALUES (201, 100, 13, 1, 129.00, 129.00);
IF NOT EXISTS (SELECT 1 FROM [OrderItems] WHERE [Id] = 202) INSERT INTO [OrderItems] ([Id], [OrderId], [MenuItemId], [Quantity], [UnitPrice], [TotalPrice]) VALUES (202, 101, 20, 1, 299.00, 299.00);
IF NOT EXISTS (SELECT 1 FROM [OrderItems] WHERE [Id] = 203) INSERT INTO [OrderItems] ([Id], [OrderId], [MenuItemId], [Quantity], [UnitPrice], [TotalPrice]) VALUES (203, 101, 23, 1, 99.00, 99.00);
IF NOT EXISTS (SELECT 1 FROM [OrderItems] WHERE [Id] = 204) INSERT INTO [OrderItems] ([Id], [OrderId], [MenuItemId], [Quantity], [UnitPrice], [TotalPrice]) VALUES (204, 101, 24, 1, 149.00, 149.00);
IF NOT EXISTS (SELECT 1 FROM [OrderItems] WHERE [Id] = 205) INSERT INTO [OrderItems] ([Id], [OrderId], [MenuItemId], [Quantity], [UnitPrice], [TotalPrice]) VALUES (205, 102, 30, 1, 299.00, 299.00);
IF NOT EXISTS (SELECT 1 FROM [OrderItems] WHERE [Id] = 206) INSERT INTO [OrderItems] ([Id], [OrderId], [MenuItemId], [Quantity], [UnitPrice], [TotalPrice]) VALUES (206, 102, 33, 1, 199.00, 199.00);
IF NOT EXISTS (SELECT 1 FROM [OrderItems] WHERE [Id] = 207) INSERT INTO [OrderItems] ([Id], [OrderId], [MenuItemId], [Quantity], [UnitPrice], [TotalPrice]) VALUES (207, 103, 50, 1, 349.00, 349.00);
IF NOT EXISTS (SELECT 1 FROM [OrderItems] WHERE [Id] = 208) INSERT INTO [OrderItems] ([Id], [OrderId], [MenuItemId], [Quantity], [UnitPrice], [TotalPrice]) VALUES (208, 103, 55, 1, 49.00, 49.00);
IF NOT EXISTS (SELECT 1 FROM [OrderItems] WHERE [Id] = 209) INSERT INTO [OrderItems] ([Id], [OrderId], [MenuItemId], [Quantity], [UnitPrice], [TotalPrice]) VALUES (209, 104, 70, 2, 179.00, 358.00);
IF NOT EXISTS (SELECT 1 FROM [OrderItems] WHERE [Id] = 210) INSERT INTO [OrderItems] ([Id], [OrderId], [MenuItemId], [Quantity], [UnitPrice], [TotalPrice]) VALUES (210, 104, 72, 1, 199.00, 199.00);
IF NOT EXISTS (SELECT 1 FROM [OrderItems] WHERE [Id] = 211) INSERT INTO [OrderItems] ([Id], [OrderId], [MenuItemId], [Quantity], [UnitPrice], [TotalPrice]) VALUES (211, 105, 90, 1, 349.00, 349.00);
IF NOT EXISTS (SELECT 1 FROM [OrderItems] WHERE [Id] = 212) INSERT INTO [OrderItems] ([Id], [OrderId], [MenuItemId], [Quantity], [UnitPrice], [TotalPrice]) VALUES (212, 105, 93, 1, 199.00, 199.00);
IF NOT EXISTS (SELECT 1 FROM [OrderItems] WHERE [Id] = 213) INSERT INTO [OrderItems] ([Id], [OrderId], [MenuItemId], [Quantity], [UnitPrice], [TotalPrice]) VALUES (213, 106, 60, 1, 499.00, 499.00);
IF NOT EXISTS (SELECT 1 FROM [OrderItems] WHERE [Id] = 214) INSERT INTO [OrderItems] ([Id], [OrderId], [MenuItemId], [Quantity], [UnitPrice], [TotalPrice]) VALUES (214, 107, 125, 2, 8.99, 17.98);
IF NOT EXISTS (SELECT 1 FROM [OrderItems] WHERE [Id] = 215) INSERT INTO [OrderItems] ([Id], [OrderId], [MenuItemId], [Quantity], [UnitPrice], [TotalPrice]) VALUES (215, 108, 126, 1, 12.99, 12.99);
IF NOT EXISTS (SELECT 1 FROM [OrderItems] WHERE [Id] = 216) INSERT INTO [OrderItems] ([Id], [OrderId], [MenuItemId], [Quantity], [UnitPrice], [TotalPrice]) VALUES (216, 109, 125, 1, 8.99, 8.99);
IF NOT EXISTS (SELECT 1 FROM [OrderItems] WHERE [Id] = 217) INSERT INTO [OrderItems] ([Id], [OrderId], [MenuItemId], [Quantity], [UnitPrice], [TotalPrice]) VALUES (217, 110, 10, 2, 359.10, 718.20);
IF NOT EXISTS (SELECT 1 FROM [OrderItems] WHERE [Id] = 218) INSERT INTO [OrderItems] ([Id], [OrderId], [MenuItemId], [Quantity], [UnitPrice], [TotalPrice]) VALUES (218, 111, 10, 1, 359.10, 359.10);
SET IDENTITY_INSERT [OrderItems] OFF;

-- =============================================
-- Table: RestaurantRatings (2 rows)
-- =============================================
SET IDENTITY_INSERT [RestaurantRatings] ON;
IF NOT EXISTS (SELECT 1 FROM [RestaurantRatings] WHERE [Id] = 3) INSERT INTO [RestaurantRatings] ([Id], [UserId], [RestaurantId], [Rating], [Review], [CreatedAt]) VALUES (3, 1004, 3, 5, N'Excellent food and fast delivery.', '2026-07-15 07:04:08.029');
IF NOT EXISTS (SELECT 1 FROM [RestaurantRatings] WHERE [Id] = 4) INSERT INTO [RestaurantRatings] ([Id], [UserId], [RestaurantId], [Rating], [Review], [CreatedAt]) VALUES (4, 1023, 1, 4, N' ', '2026-08-27 03:53:51.381');
SET IDENTITY_INSERT [RestaurantRatings] OFF;

